name: README build

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives the workflow permission to write to the repository

    steps:
    - uses: actions/checkout@v3
      with:
        # This token is automatically created by GitHub
        token: ${{ secrets.GITHUB_TOKEN }}
        # Important to fetch all history for git operations
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Update README
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: python update_readme.py
      
    - name: Pull and push changes
        run: |
          git config --global user.email "readme-bot@users.noreply.github.com"
          git config --global user.name "README-bot"
          git fetch origin
          git rebase origin/main
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated README with latest weather data"
          git push --force-with-lease