name: README build

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Create a new branch
      run: |
        git checkout -b update-readme-weather
        
    - name: Update README
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: python update_readme.py
      
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated README with latest weather data
        file_pattern: README.md
        branch: update-readme-weather
        push_options: '--force'
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: 'Update README with current weather data'
        body: 'Automated PR to update weather information in the README'
        branch: update-readme-weather
        base: main
        delete-branch: true