name: README build

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives the workflow permission to write to the repository

    steps:
    - uses: actions/checkout@v3
      with:
        # This token is automatically created by GitHub
        token: ${{ secrets.GITHUB_TOKEN }}
        # Important to fetch all history for git operations
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Update README
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: python update_readme.py
      
    - name: Commit and push if changed
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Updated README with latest weather data"
        git push