name: README build

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Update README
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: python update_readme.py
      
    - name: Set Git identity
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Check for changes
      id: check_changes
      run: |
        if [[ -n "$(git status --porcelain README.md)" ]]; then
          echo "::set-output name=changes_exist::true"
          echo "Changes detected in README.md"
        else
          echo "::set-output name=changes_exist::false"
          echo "No changes detected in README.md"
        fi

    - name: Clear untracked files
      run: |
        # Remove untracked files that may prevent rebase
        git clean -fd

    - name: Commit and push changes
      if: steps.check_changes.outputs.changes_exist == 'true'
      run: |
        # Stash any changes to avoid conflicts
        git stash -u
        
        # Fetch latest changes
        git fetch origin main
        
        # Check out main branch
        git checkout main
        
        # Rebase onto main
        git rebase origin/main
        
        # Apply stashed changes
        git stash pop
        
        # Add, commit and push
        git add README.md
        git commit -m "Updated README with latest weather data"
        git push